theme: osuny
_merge: deep
params:
  summary:
    position: hero
  search:
    active: false
  breadcrumb:
    position: after-hero
  logo:
    header: "/assets/images/logo-white.svg"
    footer: "/assets/images/logo.svg"
  persons:
    index:
      layout: grid
  posts:
    default_image: true
    index:
      options:
        categories: true